name: bluetooth_enable_fork
description: Flutter plugin to turn on bluetooth within app
version: 0.2.0
homepage: https://github.com/Alystrasz/bluetooth_enable_fork

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.hui.bluetooth_enable
        pluginClass: BluetoothEnablePlugin
      ios:
        pluginClass: BluetoothEnablePlugin
